Update Dockerfile
gautambaghel/terraform-google-terraform-cloud-agents pull request #2
Opened 2023-06-28 20:24 UTC by danbarr

* Switch back to tfc-agent user.
* Remove entrypoint/cmd override, let single execution mode be controlled by the env var.
* Explicitly tag the source image (resolves Hadolint DL3006)

2023-07-03 17:08 UTC, gautambaghel requested changes

2023-07-03 17:08 UTC, gautambaghel commented on examples/tfc-agent-gke-simple/Dockerfile
> -ENTRYPOINT ["/home/tfc-agent/bin/tfc-agent"]
@danbarr would we then specify the entry point command in the yaml file?

2023-07-03 17:08 UTC, gautambaghel commented on examples/tfc-agent-gke-simple/Dockerfile
> -ENTRYPOINT ["/home/tfc-agent/bin/tfc-agent"]
here? https://github.com/danbarr/terraform-google-terraform-cloud-agents/blob/fix-dockerfile/examples/tfc-agent-gke-simple/sample-manifests/deployment.yaml#L19

2023-07-03 20:05 UTC, danbarr commented on examples/tfc-agent-gke-simple/Dockerfile
> -ENTRYPOINT ["/home/tfc-agent/bin/tfc-agent"]
> @danbarr would we then specify the entry point command in the yaml file?

Shouldn't need to, it'll be inherited from the base container.

2023-07-04 17:52 UTC, gautambaghel commented
@danbarr  - Ahh cool! Merging now

2023-07-04 17:52 UTC, gautambaghel approved these changes

2023-07-04 17:52 UTC, merged