Splitting GKE examples into two parts, simple & custom
gautambaghel/terraform-google-terraform-cloud-agents pull request #5
Opened 2023-06-29 06:52 UTC by gautambaghel

2023-07-02 00:55 UTC, gautambaghel commented
@danbarr -- ready for your review

2023-07-06 19:36 UTC, danbarr requested changes
Made a few suggestions and one fix, but everything looks great!

2023-07-06 19:36 UTC, danbarr commented on examples/tfc-agent-gke-simple/README.md
>    - [`gke-gcloud-auth-plugin`](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke)
Not needed for the simple example anymore.

```suggestion
```

2023-07-06 19:36 UTC, danbarr commented on examples/tfc-agent-gke-custom/README.md
> +    gcloud services enable artifactregistry.googleapis.com
On my machine, I had to run a `gcloud components update` before the `gcloud artifacts` command would work - might be worth adding here?

2023-07-06 19:36 UTC, danbarr commented on modules/tfc-agent-gke/variables.tf
> +  default     = "2"
Two bytes might be a bit light 😉 

```suggestion
  default     = "2Gi"
```

2023-07-06 20:29 UTC, gautambaghel commented on modules/tfc-agent-gke/variables.tf
> +  default     = "2"
Defaults to 2Gi but explicit is better

2023-07-06 20:29 UTC, gautambaghel commented on modules/tfc-agent-gke/variables.tf
> +  default     = "2"
oh maybe not for memory

2023-07-06 20:44 UTC, gautambaghel commented on examples/tfc-agent-gke-custom/README.md
> +    gcloud services enable artifactregistry.googleapis.com
Done :) thanks for the check

2023-07-06 20:45 UTC, gautambaghel commented on examples/tfc-agent-gke-simple/README.md
>    - [`gke-gcloud-auth-plugin`](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke)
Done :) thanks for the check

2023-07-06 21:55 UTC, danbarr approved these changes
LGTM!

2023-07-06 22:21 UTC, merged